name: "mgi"

version: "1.0.0"
config-version: 2

profile: "mgi"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  mgi:
    +database: analytics
    metadata:
      +materialized: incremental
      +schema: metadata
